# 2. Feladatsor: megoldások
*(Lineáris egyenletrendszerek, felbontások)*

### P1. Feladat

Írjunk programot, amely egy adott négyzetes mátrixra kiszámolja a sarokdeterminánsait!

In [34]:
import numpy as np

def sarok_det(A: np.ndarray) -> np.array:

    v = np.zeros(np.size(A,0))

    for j in range(np.size(A,0)):
        v[j] = np.linalg.det(A[:j+1,:j+1])
    
    return(v)

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sarok_det(A)


array([ 1., -3.,  0.])

 ### P2. Feladat
 
 Írjunk programot, amely eldönti, hogy a mátrix szigorúan diagonálisan domináns-e vagy sem!

In [36]:
import numpy as np

def diag_dom(A: np.ndarray) -> bool:
    abs_sum = np.sum(np.abs(A), axis=1)
    diag_abs = 2*np.abs(np.diag(A))

    is_SD=np.all(diag_abs > abs_sum)
    return is_SD

# A = np.array([[1, 2, 5], [2, 1, 3], [5, 3, 4]])
# A = np.array([[-1, 0, 2], [0, 1, 3], [0, 1, 5]])
A = np.array([[4, 1, 1], [1, 3, 0], [2, -1, -7]])
#A = np.array([[-4, 1, 1], [1, 3, -3], [2, -1, -7]])

diag_dom(A)


np.True_

### P3. Feladat

Írjunk programot, amely kiszámítja az alábbi egyenletrendszer megoldását a Gauss-módszer segítségével! 

$$\left[\matrix{
8 & -6 & -7 & 5 \cr
2 & -1 & -2 & 1 \cr
6 & 1 & -9 & 2 \cr
-2 & -5 & 4 & 0 \cr
}\right]
\left[ \matrix{
x_1 \cr x_2 \cr x_3 \cr x_4}\right] = \left[ \matrix{
-28 \cr -7 \cr-23 \cr 8}\right]
$$


In [37]:
import numpy as np

# Maga a mátrix:
A = np.array([[8, -6, -7, 5],
              [2, -1, -2, 1],
              [6, 1, -9, 2],
              [-2, -5, 4, 0]], dtype='f')

# A jobb oldal:
b = np.array([-28, -7, -23, 8],  dtype='f').reshape(-1, 1)  # 1D tömbből 2D tömbbé alakítás

In [28]:
# Gauss-elimináció

def lu_felb(A,b):
    M = np.hstack((A, b))
    L=np.eye(np.size(A,0))
    D=np.zeros(np.shape(A))
    print('A rendszert leíró kiegészített mátrix')
    print(M)
    # U meghatározása
    for i in range(np.size(A,0)):
        # i. sor normalizálása
        L[i,i]=np.copy(M[i,i])
        M[i,i:]=M[i,i:]/M[i,i]
        
        # i. sor megfelelő együtthatókkal súlyozott változatainak
        # kivonása az alatta lévő sorokból    
        for j in range(i+1, M.shape[0]):
            L[j,i]=np.copy(M[j,i])
            M[j,:]=M[j,:]-M[j,i]*M[i,:]
        

    print('M immár felsőháromszög alakú, leszámítva az utolsó oszlopot:')
    print(M)
    print('L:')
    print(L)
    U=np.copy(M[:,:-1])

    # Visszahelyettesítés
    for j in range(np.size(A,0)-1, -1, -1):
        # j. oszlopbeli elemek kiütése;
        # ugyanezen múvelet elvégzése a hozzácsatolt, utolsó oszlopon
        M[:j, -1] -= M[j, -1] * M[:j, j]
        # ismerve a kimenetelt, nem muszáj elvégeznünk a műveletet
        M[:j, j] = 0

    print('A Gauss(-Jordan) elimináció (ideértve a visszahelyettesítést) eredménye:')
    print(M)
    return(L,U,M[:,-1])

In [39]:
 [L,U,x]=lu_felb(A,b)
L@U


A rendszert leíró kiegészített mátrix
[[  8.  -6.  -7.   5. -28.]
 [  2.  -1.  -2.   1.  -7.]
 [  6.   1.  -9.   2. -23.]
 [ -2.  -5.   4.   0.   8.]]
M immár felsőháromszög alakú, leszámítva az utolsó oszlopot:
[[ 1.    -0.75  -0.875  0.625 -3.5  ]
 [ 0.     1.    -0.5   -0.5    0.   ]
 [ 0.     0.     1.    -1.     2.   ]
 [ 0.     0.     0.     1.    -1.   ]]
L:
[[ 8.   0.   0.   0. ]
 [ 2.   0.5  0.   0. ]
 [ 6.   5.5 -1.   0. ]
 [-2.  -6.5 -1.  -3. ]]
A Gauss(-Jordan) elimináció (ideértve a visszahelyettesítést) eredménye:
[[ 1.  0.  0.  0. -2.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  1.]
 [ 0.  0.  0.  1. -1.]]


array([[ 8., -6., -7.,  5.],
       [ 2., -1., -2.,  1.],
       [ 6.,  1., -9.,  2.],
       [-2., -5.,  4.,  0.]])

In [32]:
A = np.array([[2, -1, 3],
              [4, 2, 1],
              [-6, -1, 2]], dtype='f')
b = np.array([1,1,1],  dtype='f').reshape(-1, 1)
[L,U,x]=lu_felb(A,b)
L@U

A rendszert leíró kiegészített mátrix
[[ 2. -1.  3.  1.]
 [ 4.  2.  1.  1.]
 [-6. -1.  2.  1.]]
M immár felsőháromszög alakú, leszámítva az utolsó oszlopot:
[[ 1.   -0.5   1.5   0.5 ]
 [ 0.    1.   -1.25 -0.25]
 [ 0.    0.    1.    0.5 ]]
L:
[[ 2.  0.  0.]
 [ 4.  4.  0.]
 [-6. -4.  6.]]
A Gauss(-Jordan) elimináció (ideértve a visszahelyettesítést) eredménye:
[[ 1.      0.      0.     -0.0625]
 [ 0.      1.      0.      0.375 ]
 [ 0.      0.      1.      0.5   ]]


array([[ 2., -1.,  3.],
       [ 4.,  2.,  1.],
       [-6., -1.,  2.]])

### P4. Feladat

Adjuk meg az előző feladat mátrixának LDU-felbontását!

In [40]:
# Gauss-elimináció

def ldu_felb(A,b):
    M = np.hstack((A, b))
    L=np.eye(np.size(A,0))
    D=np.zeros(np.shape(A))
    print('A rendszert leíró kiegészített mátrix')
    print(M)
    # U meghatározása
    for i in range(np.size(A,0)):
        # i. sor normalizálása
        D[i,i]=np.copy(M[i,i])
        M[i,i:]=M[i,i:]/M[i,i]
        
        # i. sor megfelelő együtthatókkal súlyozott változatainak
        # kivonása az alatta lévő sorokból    
        for j in range(i+1, M.shape[0]):
            L[j,i]=np.copy(M[j,i]/D[i,i])
            M[j,:]=M[j,:]-M[j,i]*M[i,:]
        

    print('M immár felsőháromszög alakú, leszámítva az utolsó oszlopot:')
    print(M)
    print('L:')
    print(L)
    U=np.copy(M[:,:-1])

    # Visszahelyettesítés
    for j in range(np.size(A,0)-1, -1, -1):
        # j. oszlopbeli elemek kiütése;
        # ugyanezen múvelet elvégzése a hozzácsatolt, utolsó oszlopon
        M[:j, -1] -= M[j, -1] * M[:j, j]
        # ismerve a kimenetelt, nem muszáj elvégeznünk a műveletet
        M[:j, j] = 0

    print('A Gauss(-Jordan) elimináció (ideértve a visszahelyettesítést) eredménye:')
    print(M)
    return(L,D,U,M[:,-1])

In [46]:
A = np.array([[2, -1, 3],
              [4, 2, 1],
              [-6, -1, 2]], dtype='f')
b = np.array([1,1,1],  dtype='f').reshape(-1, 1)
[L,D,U,x]=ldu_felb(A,b)
L@D@U

A rendszert leíró kiegészített mátrix
[[ 2. -1.  3.  1.]
 [ 4.  2.  1.  1.]
 [-6. -1.  2.  1.]]
M immár felsőháromszög alakú, leszámítva az utolsó oszlopot:
[[ 1.   -0.5   1.5   0.5 ]
 [ 0.    1.   -1.25 -0.25]
 [ 0.    0.    1.    0.5 ]]
L:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-3. -1.  1.]]
A Gauss(-Jordan) elimináció (ideértve a visszahelyettesítést) eredménye:
[[ 1.      0.      0.     -0.0625]
 [ 0.      1.      0.      0.375 ]
 [ 0.      0.      1.      0.5   ]]


array([[ 2., -1.,  3.],
       [ 4.,  2.,  1.],
       [-6., -1.,  2.]])

### P5. Feladat

Írjunk programot, amely megadja az alábbi mátrix  Cholesky-felbontását!

$$A =  \left[\matrix{ 
4 & 2 & 1\cr
2 & 17 & 13/2 \cr
1 & 13/2 & 23/2
}\right]$$

In [50]:
A=np.array([[4,2,1],[2,17,13/2],[1,13/2,23/2]])
[L,D,U,x]=ldu_felb(A,np.ones([3,1]))

G=L@D**(1/2)
print(G)
print(G@G.T)

A rendszert leíró kiegészített mátrix
[[ 4.   2.   1.   1. ]
 [ 2.  17.   6.5  1. ]
 [ 1.   6.5 11.5  1. ]]
M immár felsőháromszög alakú, leszámítva az utolsó oszlopot:
[[1.      0.5     0.25    0.25   ]
 [0.      1.      0.375   0.03125]
 [0.      0.      1.      0.0625 ]]
L:
[[1.    0.    0.   ]
 [0.5   1.    0.   ]
 [0.25  0.375 1.   ]]
A Gauss(-Jordan) elimináció (ideértve a visszahelyettesítést) eredménye:
[[1.         0.         0.         0.23046875]
 [0.         1.         0.         0.0078125 ]
 [0.         0.         1.         0.0625    ]]
[[2.  0.  0. ]
 [1.  4.  0. ]
 [0.5 1.5 3. ]]
[[ 4.   2.   1. ]
 [ 2.  17.   6.5]
 [ 1.   6.5 11.5]]
