# 4. Feladatsor: megoldások

*(Nemlineáris egyenletek: intervallumfelezés, fixpont iteráció)*

### 4. Feladat
Keressük meg az $f(x) = x^3 + 2 x^2 + 10 x - 20$ egyenlet gyökét, ha valahonnan sejtjük, hogy a $K=[1,2]$  intervallumban van. Alkalmazzunk fixpont-iterációt és addig iteráljunk, míg a szomszédos iteráltak távolsága $10^{-10}$ alá nem csökken.

Megoldás: Az iterációs függvény a következő lesz: $F(x)=x-\omega(x^3 + 2 x^2 + 10 x - 20)$ megfelelő $\omega$ mellett, hiszen ennek fixpontja $x=x-\omega(x^3 + 2 x^2 + 10 x - 20)$ megoldja az $x^3 + 2 x^2 + 10 x - 20=0$ egyenletet, és megfelelő $\omega$ mellett kontrakció lesz. Számoljunk ki egy megfelelő $\omega$-át! Ha $\max_{K}|F'(x)|=L<1$ és $F$ ráképezés, akkor kontrakció is, hiszen ekkor $F$ Lipschitz folytonos is $L$ Lipschitz konstanssal. Minimalizáljuk ezt. 

$$F'(x)=1-\omega(3x^2+4x+10)$$

Mivel $F$ monoton növő $K$-n így $\max_{[1,2]}|F'(x)|=\max \{|1-\omega (3\cdot 1^2+4\cdot 1 +10)|,|1-\omega (3\cdot 2^2+4\cdot 2 +10|)\} =\max\{|1-\omega \cdot 17|,|1-\omega\cdot 30|\}$, ez $\omega=\dfrac{2}{17+30}$ esetén lesz minimális. 

In [4]:
import numpy as np

def fixpont_it(x0, f, atol, max_it):
    x = x0
    for num_steps in range(1, max_it + 1):
        dx = f(x)-x
        x = x + dx
        if np.abs(dx) < atol:
            break
    return x, num_steps


def f(x):
    return x-2/47*(x**3+2*x**2+10*x-20)

a, num = fixpont_it(2,f,10**(-10),100)

print(a,num)
print(f(a)-a)

1.3688081078142509 11
6.3933303096064265e-12


# próba ZH feladatok

In [1]:
import numpy as np
import math

def binomial_matrix(n):
    A = np.zeros((n,n), dtype=int)
    
    for i in range(n):
        for j in range(i+1):
            A[i,j] = math.comb(i, j)
            
    return A

# példa
print(binomial_matrix(4))

[[1 0 0 0]
 [1 1 0 0]
 [1 2 1 0]
 [1 3 3 1]]


In [2]:
import numpy as np

def x_value(A):
    A = np.array(A, dtype=float)

    inv_norm = np.linalg.norm(np.linalg.inv(A), 2)
    s = np.sum(np.abs(A)**3)**(1/3)

    return inv_norm * s


def b_value(A):
    A = np.array(A, dtype=float)

    if A.shape[0] == A.shape[1]:
        return x_value(A)
    else:
        return np.sqrt(x_value(A.T @ A))


# példa
A = np.array([[1,2],[3,4]])
print(b_value(A))

12.683108310278286


In [3]:
import numpy as np

def solve_iterative(A, b, x0, c, itnum=1000):
    A = np.array(A, dtype=float)
    b = np.array(b, dtype=float)
    x = np.array(x0, dtype=float)
    is_success=False
    # 1. lépés: fixpont iteráció

    for i in range(1,itnum+1):
        x_new = x - c * (A @ x - b)
        k = i
        if np.linalg.norm(x_new - x) < 0.25:
            is_success=True
            break

        x = x_new
        

    x = x_new

    #  2. lépés: Jacobi iteráció
    D = np.diag(np.diag(A))
    R = A - D
    D_inv = np.linalg.inv(D)

    for _ in range(k):
        x = D_inv @ (b - R @ x)

    # visszaadjuk a megoldást és A*x-et
    return x, A @ x, k

In [4]:
A = np.array([[2,-1],
              [-1,2]], dtype=float)

b = np.array([1,3], dtype=float)
x0 = np.array([100,100], dtype=float)

[x,b,k]=solve_iterative(A, b, x0, 0.5)
print(x)
print(b)
print(k)

[1.66676044 2.33342648]
[1.00009441 3.00009251]
10
